### ISSUE TITLE
What is the process?

### ISSUE THREAD

**Issue by lanshark** [jazzband/site#6]
Hi All,

LOVE the idea of Jazzband, but a bit unsure of 'how it works'...

For instance, I've just joined, and actually created a PR of the site, mostly cleaning up/correcting grammar and language issues. I've posted the PR here.

Obviously, I *COULD* merge it, and force the change.

But, what is the 'desired process'?  Is there a Code Review?  Do I need to get approval of some number of other members?  What should the desired process be?  

Second, How do I know if anyone is working a particular issue?  I would rather collaborate, or attack a different issue, than duplicate work. 

I'm sure this is a new experiment, but I thought I'd kick off the discussion anyway.

-Scott

**Comment by blueyed** [comment]
Apart from that, I totally understand you.

A good read in this context is http://hintjens.com/blog:106.

I'd say that everything should be ACKed by somebody else at least, even for trivial documentation changes, which allows for training / trying the process.

With some bigger things like https://github.com/jazzband/django-configurations/pull/131, I wanted to wait for feedback from more contributors, and merged it when there were 3 thumbs up.

I think the procedure might be different for each repo, e.g. depending on the number of active contributors etc.

(This should be discussed at https://github.com/jazzband/roadies maybe? - although the "site" repo would be the place to discuss it.  See also https://github.com/jazzband/roadies/issues/2, which is related / relevant).

**Comment by lanshark** [comment]
I think there need to be some guidelines for how this stuff 'should' happen, though each project is, of course, able to modify as it see's fit.  I'm trying to be a good citizen, and also start the discussion.

**Comment by blueyed** [comment]
> I think there need to be some guidelines for how this stuff 'should' happen

:+1:

**Comment by jezdez** [comment]
Ooops, I totally missed this issue folks, I had forgotten to watch the repo. In general those discussions should go into the roadies repo since as it's more about policy than actual problems with the site.

I'll work on updating the FAQ next week to fix some of those questions that have come up, that we do already have plans but hadn't time yet to formulate precisely enough. Thanks for getting back to us though, this is super helpful.
